<?php
global $nukeurl, $sitename;

//
//Administration
//
define('_SMADMIN','Site Map Administration');
define('_SMMAINADMIN','Site Administration');

//Admin Menu
define('_SMGENCONFIG','General Configuration');
define('_SMGENCONFIGDESC','Change the general behaviour of the Site Map Module');
define('_SMMODS','Modules/Addons');
define('_SMMODSDESC','Enable/Disable Modules and Addons');
define('_SMLIMITS','Limit Links');
define('_SMLIMITSDESC','Limit the amount of links generated by the Site Map Module regarding certain Modules and Addons');
define('_SMGOOGLESETUP','Google Block Setup');
define('_SMGOOGLESETUPDESC','Some Google Block settings you might like to change');

//General Configuration
define('_SMMATCHTHEME','Enable Match Theme');
define('_SMSOMMAIRE','Enable Sommaire Block');
define('_SMGT','Enable GT-NExtGEn (GoogleTap)');
define('_SMGOOGLE','Enable Google Search Block');
define('_SMGENTIME','Enable Page Generation');

define('_SMEMATCHTHEME','This will change the script to match your theme');
define('_SMESOMMAIRE','If you use the Sommaire block, enable it');
define('_SMGOTGT','If GoogleTap installed, enabled it');
define('_SMEGOOGLE','Show Google Block?');
define('_SMEGENTIME','Show Page Generation?');

//Modules/Addons
define('_SMNEWS','Enable News');
define('_SMFNA','Enable ForumNews Advance');
define('_SMFORUMCAT','Enable Forum Categories');
define('_SMFORUMS','Enable Forums');
define('_SMFORUMTOPICS','Enable Forum Topics');
define('_SMKB','Enable Knowledge Base');
define('_SMDL','Enable Downloads');
define('_SMWL','Enable Web Links');
define('_SMFAQ','Enable FAQ');
define('_SMCONTENT','Enable Content');
define('_SMREVIEWS','Enable Reviews');
define('_SMTUTORIALS','Enable Tutorials');
define('_SMPJ','Enable Projects');
define('_SMSUPPORTERS','Enable Supporters');
define('_SMCOPPERMINE','Enable coppermine Gallery');
define('_SMSPCHAT','Enable SPChat');
define('_SMSHOUTS','Enable Shouts');
define('_SMARCADE','Enable Arcade Games');
define('_SMRSS','Enable RSS Feeds');

//Limit Links
define('_SMLIMITNEWS','News Links');
define('_SMLIMITFNA','ForumNews Advance');
define('_SMLIMITFORUMTOPICS','Forum Topics');
define('_SMLIMITKB','Knowledge Base');
define('_SMLIMITDL','Downloads');
define('_SMLIMITWL','Web Links');
define('_SMLIMITCONTENT','Content');
define('_SMLIMITREVIEWS','Reviews');
define('_SMLIMITTUTORIALS','Tutorials');
define('_SMLIMITPJ','Projects');
define('_SMLIMITSUPPORTERS','Supporters');
define('_SMLIMITCOP','coppermine Pictures');
define('_SMLIMITSHOUTS','Shouts');
define('_SMLIMITARCADE','Arcade Games');

//Google Block Setup
define('_SMSITELOGO','Site Logo Name (default: logo.gif)');
define('_SMSITELOGOPATH','Site Logo Path (default: images/)');
define('_SMSITELOGOHEIGHT','Site Logo Height (max. 50)');
define('_SMSITELOGOWIDTH','Site Logo Width (default: 425)');
define('_SMSITELOGOHEADER','Search Result Page Header (default: #ffffff)');
define('_SMSITELOGOBG','Search Result Page Background (default: #ffffff)');
define('_SMGOOGLELOGO','Google Logo Name (default: google.gif)');
define('_SMGOOGLELOGOPATH','Google Logo Path (default: images/powered/)');

//
// Module
//
define("_SM","Site Map");
define("_SM_VIEWING","You are currently viewing Site Map index page.<br />We suggest to look at the <a href=\"".$nukeurl."\">original content</a>.<p><br /><br />");
define("_SM_GOOGLE","Google Web &amp; ".$sitename." Domain Search");
define("_SM_HOME","Home");
define("_SM_ACTIVE_MODULES","Active Modules");
define("_SM_NEWS","News");
define("_SM_NEWS_ART"," News Articles");
define("_SM_LATEST","Latest ");
define("_SM_TOP","Top ");
define("_SM_FNA","ForumNews");
define("_SM_FNA_TOPICS"," ForumNews Topics");
define("_SM_FNA_CAT"," ForumNews Categories");
define("_SM_FORUMS","Forums");
define("_SM_FORUM_CAT","Forum Categories");
define("_SM_PUB_FORUM","Public Forums");
define("_SM_PUB_TOPICS_FNA"," Public Topics (without ForumNews Advance Topics)");
define("_SM_PUB_TOPICS"," Public Topics");
define("_SM_KB_CAT","Knowledge Base Categories");
define("_SM_KB_ART"," Knowledge Base Articles");
define("_SM_DL"," Downloads");
define("_SM_WL"," Web Links");
define("_SM_FAQ","General FAQs");
define("_SM_CONTENT"," pages from Content");
define("_SM_REVIEWS"," Reviews");
define("_SM_TUTORIALS_CAT","Tutorials Categories");
define("_SM_TUTORIALS_ART"," Tutorials Articles");
define("_SM_PROJECTS"," Projects");
define("_SM_SUPPORTERS"," Supporters");
define("_SM_HITS","Hits ");
define("_SM_COP_GAL_CAT","coppermine Gallery Categories");
define("_SM_COP_GAL_ALB","coppermine Gallery Albums");
define("_SM_COP_GAL_PIC"," coppermine Gallery Pictures");
define("_SM_SPCHAT_ROOMS","SPChat Rooms");
define("_SM_SHOUT_BOX"," shouts from Shout Box");
define("_SM_ARCADE"," Arcade Games");
define("_SM_RSS","RSS Syndications");
define("_SM_CREDITS","<br />This page was generated by <a href=\"http://www.evolved-systems.net\">Site Map Module</a> ");
define("_SM_SUPPORT","<br /><br />Please support development at:<br /><a href=\"http://www.evolved-systems.net\" target=\"_blank\">evolved-Systems.net</a><br /><a href=\"http://www.nuke-evolution.com\" target=\"_blank\">Nuke-Evolution.com</a>");
define("_SM_DBCONFIG","Database Error. Please notify the webmaster to run their site map configuration!");

?>